import React, { useEffect, useState, useCallback, useMemo } from 'react';
import { StringInputProps, set, unset, useFormValue } from 'sanity';
import { TextInput, TextArea, Box, Text } from '@sanity/ui';
import * as wanakana from 'wanakana';

/**
 * AutoRomajiInput
 * Komponen yang secara otomatis menghasilkan Romaji dari field Furigana/Hiragana.
 * Mendukung 'Smart-Sync': Memungkinkan pengeditan manual tanpa tertimpa otomatis.
 */
export function AutoRomajiInput(props: StringInputProps) {
  const { value, onChange, elementProps, path, schemaType } = props;
  
  // Ambil nama field sumber dari opsi skema, default ke 'furigana'
  const sourceFieldName = (schemaType.options as any)?.sourceField || 'furigana';

  // Konstruksi path untuk field sumber (sibling field)
  // Jika field ini ada di dalam object/array, kita ambil prefix path-nya
  const sourcePath = useMemo(() => {
    const parentPath = path.slice(0, -1);
    return [...parentPath, sourceFieldName];
  }, [path, sourceFieldName]);

  // Pantau nilai dari field sumber secara real-time
  const sourceValueRaw = useFormValue(sourcePath) as any;

  // Helper untuk mengekstrak teks murni dari Portable Text (array of blocks)
  const extractPlainText = (blocks: any): string => {
    if (typeof blocks === 'string') return blocks;
    if (!Array.isArray(blocks)) return '';
    return blocks
      .map((block) => {
        if (block._type !== 'block' || !block.children) return '';
        return block.children.map((child: any) => child.text).join('');
      })
      .join('\n');
  };

  const sourceValue = useMemo(() => extractPlainText(sourceValueRaw), [sourceValueRaw]);

  // State untuk melacak hasil generate terakhir guna mendeteksi edit manual
  const [lastAutoGenerated, setLastAutoGenerated] = useState<string>('');

  useEffect(() => {
    if (sourceValue) {
      const generated = wanakana.toRomaji(sourceValue);
      
      // LOGIKA SMART-SYNC:
      // Kita hanya update otomatis jika:
      // 1. Field saat ini kosong (pemuatan awal atau dihapus user)
      // 2. ATAU nilai saat ini masih sama dengan apa yang kita generate sebelumnya (user belum mengubahnya)
      if (!value || value === lastAutoGenerated) {
        if (value !== generated) {
          onChange(set(generated));
          queueMicrotask(() => {
            setLastAutoGenerated(generated);
          });
        }
      }
    } else if (!sourceValue && value === lastAutoGenerated && value !== '') {
      // Jika sumber dihapus dan nilai saat ini adalah hasil generate, bersihkan juga
      onChange(unset());
      queueMicrotask(() => {
        setLastAutoGenerated('');
      });
    }
  }, [sourceValue, value, lastAutoGenerated, onChange]);

  const handleChange = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      const nextValue = event.currentTarget.value;
      // Saat user mengetik manual, state 'lastAutoGenerated' tidak akan sinkron lagi dengan 'value',
      // sehingga otomatisasi akan berhenti sampai field dikosongkan.
      onChange(nextValue ? set(nextValue) : unset());
    },
    [onChange]
  );

  const isManual = value && value !== lastAutoGenerated;

  const isTextArea = schemaType.jsonType === 'string' && schemaType.name === 'text';
  const InputComponent = isTextArea ? TextArea : TextInput;

  return (
    <Box>
      <InputComponent
        {...elementProps}
        value={value || ''}
        onChange={handleChange}
        placeholder={`Otomatis dari ${sourceFieldName}...`}
        style={isManual ? { borderLeft: '3px solid var(--card-accent-color, #2196f3)' } : {}}
        rows={isTextArea ? 5 : undefined}
      />
      {isManual && (
        <Text size={1} muted style={{ marginTop: '4px', fontSize: '10px' }}>
          💡 <i>Mode Manual Aktif. Kosongkan field untuk kembali ke otomatis.</i>
        </Text>
      )}
    </Box>
  );
}
