import React, { useEffect, useRef, useCallback, useMemo, useState } from 'react';
import { StringInputProps, set, unset, useFormValue } from 'sanity';
import { TextInput, TextArea, Box, Text, Spinner, Flex } from '@sanity/ui';
import * as wanakana from 'wanakana';

/**
 * AutoFuriganaInput
 * Komponen Sanity kustom yang secara otomatis mengonversi teks Jepang (termasuk Kanji)
 * menjadi Hiragana melalui API /api/furigana.
 */
export function AutoFuriganaInput(props: StringInputProps) {
  const { value, onChange, elementProps, path, schemaType } = props;
  const inputRef = useRef<HTMLInputElement>(null);
  const [isLoading, setIsLoading] = useState(false);

  // Ambil nama field sumber dari opsi skema
  const sourceFieldName = (schemaType.options as any)?.sourceField;

  // Konstruksi path untuk field sumber
  const sourcePath = useMemo(() => {
    if (!sourceFieldName) return null;
    const parentPath = path.slice(0, -1);
    return [...parentPath, sourceFieldName];
  }, [path, sourceFieldName]);

  // Pantau nilai dari field sumber
  const sourceValueRaw = useFormValue(sourcePath || []) as any;

  // Helper untuk mengekstrak teks murni dari Portable Text
  const extractPlainText = (blocks: any): string => {
    if (typeof blocks === 'string') return blocks;
    if (!Array.isArray(blocks)) return '';
    return blocks
      .map((block) => {
        if (block._type !== 'block' || !block.children) return '';
        return block.children.map((child: any) => child.text).join('');
      })
      .join('\n');
  };

  const sourceValue = useMemo(() => extractPlainText(sourceValueRaw), [sourceValueRaw]);

  // State untuk melacak hasil generate terakhir guna mendeteksi edit manual
  const [lastAutoGenerated, setLastAutoGenerated] = useState<string>('');

  useEffect(() => {
    // Hanya proses jika ada sourceValue, sourceFieldName didefinisikan,
    // dan field saat ini kosong atau masih berisi nilai hasil otomasi sebelumnya.
    if (!sourceValue || !sourceFieldName || (value && value !== lastAutoGenerated)) {
      return;
    }

    // Cek apakah mengandung Kanji. Jika tidak ada Kanji, wanakana saja cukup (lokal & instan)
    const hasKanji = wanakana.tokenize(sourceValue).some(t => wanakana.isKanji(t));
    
    if (!hasKanji) {
        const generated = wanakana.toHiragana(sourceValue);
        if (value !== generated) {
          onChange(set(generated));
          setLastAutoGenerated(generated);
        }
        return;
    }

    // Debounce API call
    console.log("Triggering AutoFurigana fetch for:", sourceValue.substring(0, 50) + "...");
    const timeoutId = setTimeout(async () => {
      setIsLoading(true);
      try {
        const response = await fetch('/api/furigana', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ text: sourceValue }),
        });

        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();
        console.log("AutoFurigana API Result received.");
        
        if (data.hiragana && (!value || value === lastAutoGenerated)) {
          onChange(set(data.hiragana));
          setLastAutoGenerated(data.hiragana);
        } else if (data.error) {
          console.error("AutoFurigana API Error:", data.error, data.details);
        }
      } catch (error) {
        console.error("AutoFurigana Fetch Error:", error);
      } finally {
        setIsLoading(false);
      }
    }, 800);

    return () => clearTimeout(timeoutId);
  }, [sourceValue, value, lastAutoGenerated, onChange, sourceFieldName]);

  const handleChange = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      const nextValue = event.currentTarget.value;
      // Tetap izinkan input manual (dengan konversi romaji -> kana instan)
      const kanaValue = wanakana.toHiragana(nextValue, { IMEMode: true });
      onChange(kanaValue ? set(kanaValue) : unset());
    },
    [onChange]
  );

  const isManual = sourceFieldName && value && value !== lastAutoGenerated;
  const isTextArea = schemaType.jsonType === 'string' && schemaType.name === 'text';
  const InputComponent = isTextArea ? TextArea : TextInput;

  return (
    <Box>
      <Flex align="center" style={{ position: 'relative' }}>
        <Box flex={1}>
          <InputComponent
            {...elementProps}
            ref={inputRef as any}
            value={value || ''}
            onChange={handleChange}
            placeholder={sourceFieldName ? `Otomatis mengonversi ${sourceFieldName}...` : "Ketik Hiragana..."}
            style={isManual ? { borderLeft: '3px solid var(--card-accent-color, #2196f3)' } : {}}
            rows={isTextArea ? 5 : undefined}
          />
        </Box>
        {isLoading && (
          <Box style={{ position: 'absolute', right: '10px', zIndex: 10 }}>
            <Spinner />
          </Box>
        )}
      </Flex>
      
      {isManual && (
        <Text size={1} muted style={{ marginTop: '4px', fontSize: '10px' }}>
          💡 <i>Mode Manual Aktif. Kosongkan field untuk kembali ke otomatis (AI/Kuroshiro).</i>
        </Text>
      )}
    </Box>
  );
}
