import React, { useEffect, useRef, useCallback, useMemo, useState } from 'react';
import { StringInputProps, set, unset, useFormValue } from 'sanity';
import { TextInput, TextArea, Box, Text } from '@sanity/ui';
import * as wanakana from 'wanakana';

/**
 * KanaInput
 * Komponen yang mengubah Romaji menjadi Hiragana secara real-time.
 * Sekarang mendukung 'Smart-Sync': Otomatis generate dari field sumber (misal: 'word').
 */
export function KanaInput(props: StringInputProps) {
  const { value, onChange, elementProps, path, schemaType } = props;
  const inputRef = useRef<HTMLInputElement>(null);

  // Ambil nama field sumber dari opsi skema
  const sourceFieldName = (schemaType.options as any)?.sourceField;

  // Konstruksi path untuk field sumber
  const sourcePath = useMemo(() => {
    if (!sourceFieldName) return null;
    const parentPath = path.slice(0, -1);
    return [...parentPath, sourceFieldName];
  }, [path, sourceFieldName]);

  // Pantau nilai dari field sumber
  const sourceValueRaw = useFormValue(sourcePath || []) as any;

  // Helper untuk mengekstrak teks murni dari Portable Text (array of blocks)
  const extractPlainText = (blocks: any): string => {
    if (typeof blocks === 'string') return blocks;
    if (!Array.isArray(blocks)) return '';
    return blocks
      .map((block) => {
        if (block._type !== 'block' || !block.children) return '';
        return block.children.map((child: any) => child.text).join('');
      })
      .join('\n');
  };

  const sourceValue = useMemo(() => extractPlainText(sourceValueRaw), [sourceValueRaw]);

  // State untuk melacak hasil generate terakhir guna mendeteksi edit manual
  const [lastAutoGenerated, setLastAutoGenerated] = useState<string>('');

  useEffect(() => {
    if (sourceValue && sourceFieldName) {
      // Gunakan wanakana untuk convert ke Hiragana
      const generated = wanakana.toHiragana(sourceValue);
      
      // LOGIKA SMART-SYNC:
      // Hanya update jika field kosong atau masih berisi hasil generate sebelumnya
      if (!value || value === lastAutoGenerated) {
        if (value !== generated) {
          onChange(set(generated));
          setLastAutoGenerated(generated);
        }
      }
    } else if (!sourceValue && sourceFieldName && value === lastAutoGenerated && value !== '') {
      onChange(unset());
      setLastAutoGenerated('');
    }
  }, [sourceValue, value, lastAutoGenerated, onChange, sourceFieldName]);

  const handleChange = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      const nextValue = event.currentTarget.value;
      
      // Fitur asli: Convert romaji ke kana saat mengetik
      const kanaValue = wanakana.toHiragana(nextValue, { IMEMode: true });
      
      onChange(kanaValue ? set(kanaValue) : unset());
    },
    [onChange]
  );

  const isManual = sourceFieldName && value && value !== lastAutoGenerated;
  const isTextArea = schemaType.jsonType === 'string' && schemaType.name === 'text';
  const InputComponent = isTextArea ? TextArea : TextInput;

  return (
    <Box>
      <InputComponent
        {...elementProps}
        ref={inputRef as any}
        value={value || ''}
        onChange={handleChange}
        placeholder={sourceFieldName ? `Otomatis dari ${sourceFieldName}...` : "Ketik romaji, otomatis jadi Hiragana..."}
        style={isManual ? { borderLeft: '3px solid var(--card-accent-color, #2196f3)' } : {}}
        rows={isTextArea ? 5 : undefined}
      />
      {isManual && (
        <Text size={1} muted style={{ marginTop: '4px', fontSize: '10px' }}>
          💡 <i>Mode Manual Aktif. Kosongkan field untuk kembali ke otomatis.</i>
        </Text>
      )}
    </Box>
  );
}
